/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CgmlVersion = number | string;
export type Meta = {
  [k: string]: unknown;
} | null;
export type Imports = unknown[] | null;
export type ComponentTypes = {
  [k: string]: {
    [k: string]: ComponentTypeDef;
  };
} | null;
export type Composition = unknown[] | null;
export type Ordering = string | null;
export type Visibility = {
  [k: string]: unknown;
} | null;
export type RankHierarchy = (string | number)[] | null;
export type Decks = {
  [k: string]: DeckInstance;
} | null;
export type Type = string;
export type Meta1 = {
  [k: string]: unknown;
} | null;
export type Zones = ZoneInstance[] | null;
export type Name = string;
export type Type1 = string;
export type OfDeck = string | null;
export type PerPlayer = boolean | null;
export type Meta2 = {
  [k: string]: unknown;
} | null;
export type Variables = VariableInstance[] | null;
export type Name1 = string;
export type PerPlayer1 = boolean | null;
export type Meta3 = {
  [k: string]: unknown;
} | null;
export type Action1 = string;
export type Params = {
  [k: string]: unknown;
} | null;
export type From = string | null;
export type FromDeck = string | null;
export type To = string | null;
export type Target = string | null;
export type Count =
  | number
  | {
      [k: string]: unknown;
    }
  | null;
export type Player = string | null;
export type Prompt = string | null;
export type StoreAs = string | null;
export type Setup = Action[];
export type Phases = string[] | null;
export type Meta4 = {
  [k: string]: unknown;
} | null;
export type InitialState = string;
export type PlayerOrder = string;
export type Transitions = Transition[] | null;
export type From1 = string;
export type To1 = string;
export type Isequal = Operand[] | null;
export type Path = string | null;
export type Ref = string | null;
export type Isequal1 = Operand[] | null;
export type Isgreaterthan = Operand[] | null;
export type Islessthan = Operand[] | null;
export type And = Operand[] | null;
export type Or = Operand[] | null;
export type Any = Operand[] | null;
export type All = Operand[] | null;
export type Max = Operand[] | null;
export type Min = Operand[] | null;
export type Sum = Operand[] | null;
export type Count1 = Operand[] | null;
export type Distinct = Operand[] | null;
export type Filter1 = Operand[] | null;
export type Map = Operand[] | null;
export type Isgreaterthan1 = Operand[] | null;
export type Islessthan1 = Operand[] | null;
export type And1 = Condition1[] | null;
export type Or1 = Condition1[] | null;
export type Any1 = Condition1[] | null;
export type All1 = Condition1[] | null;
export type Max1 = Operand[] | null;
export type Min1 = Operand[] | null;
export type Sum1 = Operand[] | null;
export type Count2 = Operand[] | null;
export type Filter2 = Condition1[] | null;
export type Distinct1 = Operand[] | null;
export type WinCondition = {
  [k: string]: unknown;
} | null;
export type Meta5 = {
  [k: string]: unknown;
} | null;
export type Id = string;
export type Trigger = string;
export type Effect = EffectAction[] | null;
export type Action2 = string;
export type Params1 = {
  [k: string]: unknown;
} | null;
export type From2 = string | null;
export type To2 = string | null;
export type Player1 = string | null;
export type Target1 = string | null;
export type Count3 =
  | number
  | {
      [k: string]: unknown;
    }
  | null;
export type Prompt1 = string | null;
export type StoreAs1 = string | null;
export type State = string | null;
export type Description = string | null;
export type Meta6 = {
  [k: string]: unknown;
} | null;
export type Rules = Rule[];

export interface CgmlDefinition {
  cgml_version: CgmlVersion;
  meta: Meta;
  imports?: Imports;
  components: Components;
  setup: Setup;
  flow: Flow;
  rules: Rules;
  [k: string]: unknown;
}
export interface Components {
  component_types?: ComponentTypes;
  decks?: Decks;
  zones?: Zones;
  variables?: Variables;
  meta?: Meta3;
  [k: string]: unknown;
}
export interface ComponentTypeDef {
  composition?: Composition;
  ordering?: Ordering;
  visibility?: Visibility;
  rank_hierarchy?: RankHierarchy;
  [k: string]: unknown;
}
export interface DeckInstance {
  type: Type;
  meta?: Meta1;
  [k: string]: unknown;
}
export interface ZoneInstance {
  name: Name;
  type: Type1;
  of_deck?: OfDeck;
  per_player?: PerPlayer;
  meta?: Meta2;
  [k: string]: unknown;
}
export interface VariableInstance {
  name: Name1;
  per_player?: PerPlayer1;
  initial_value?: unknown;
  computed?: unknown;
  [k: string]: unknown;
}
export interface Action {
  action: Action1;
  params?: Params;
  from?: From;
  from_deck?: FromDeck;
  to?: To;
  target?: Target;
  count?: Count;
  filter?: unknown;
  player?: Player;
  prompt?: Prompt;
  store_as?: StoreAs;
  value?: unknown;
  condition?: unknown;
  [k: string]: unknown;
}
export interface Flow {
  states: States;
  initial_state: InitialState;
  player_order: PlayerOrder;
  transitions?: Transitions;
  win_condition?: WinCondition;
  meta?: Meta5;
  [k: string]: unknown;
}
export interface States {
  [k: string]: StateDef;
}
export interface StateDef {
  phases?: Phases;
  meta?: Meta4;
  [k: string]: unknown;
}
export interface Transition {
  from: From1;
  to: To1;
  condition?: Condition1 | null;
  [k: string]: unknown;
}
export interface Condition1 {
  isEqual?: Isequal;
  isGreaterThan?: Isgreaterthan1;
  isLessThan?: Islessthan1;
  and?: And1;
  or?: Or1;
  not?: Condition1 | null;
  any?: Any1;
  all?: All1;
  max?: Max1;
  min?: Min1;
  sum?: Sum1;
  count?: Count2;
  filter?: Filter2;
  distinct?: Distinct1;
  group_by?: unknown;
  having?: unknown;
  [k: string]: unknown;
}
export interface Operand {
  path?: Path;
  value?: unknown;
  ref?: Ref;
  isEqual?: Isequal1;
  isGreaterThan?: Isgreaterthan;
  isLessThan?: Islessthan;
  and?: And;
  or?: Or;
  not?: Operand | null;
  any?: Any;
  all?: All;
  max?: Max;
  min?: Min;
  sum?: Sum;
  count?: Count1;
  distinct?: Distinct;
  filter?: Filter1;
  map?: Map;
  group_by?: unknown;
  having?: unknown;
  [k: string]: unknown;
}
export interface Rule {
  id: Id;
  trigger: Trigger;
  condition?: Condition1 | null;
  effect?: Effect;
  description?: Description;
  meta?: Meta6;
  [k: string]: unknown;
}
export interface EffectAction {
  action: Action2;
  params?: Params1;
  from?: From2;
  to?: To2;
  player?: Player1;
  target?: Target1;
  count?: Count3;
  filter?: unknown;
  value?: unknown;
  prompt?: Prompt1;
  store_as?: StoreAs1;
  condition?: unknown;
  state?: State;
  [k: string]: unknown;
}
